### ISSUE TITLE
Concurrency issues

### ISSUE THREAD

**Issue by promontis** [IdentityServer/IdentityServer3.EntityFramework#42]
Hi guys!

Today I got the exception below. I'm trying to access my API in two async methods (to load items 0 to 20 as a 'batch' and then the control tries to see if there are more items to load (so 20 to 40)). When the token has been expired it tries to refresh it, but it seems that this happens at the same time and that some concurrency issues are in place.

I think we should do something like:
https://msdn.microsoft.com/en-us/library/vstudio/bb738618(v=vs.100).aspx

What do you guys think?

```
iisexpress.exe Information: 0 : [Thinktecture.IdentityServer.Core.ResponseHandling.TokenResponseGenerator]: 2/22/2015 7:36:04 PM -- Creating token response
iisexpress.exe Information: 0 : [Thinktecture.IdentityServer.Core.ResponseHandling.TokenResponseGenerator]: 2/22/2015 7:36:04 PM -- Creating token response
iisexpress.exe Information: 0 : [Thinktecture.IdentityServer.Core.ResponseHandling.TokenResponseGenerator]: 2/22/2015 7:36:04 PM -- Creating token response
iisexpress.exe Information: 0 : [Thinktecture.IdentityServer.Core.ResponseHandling.TokenResponseGenerator]: 2/22/2015 7:36:05 PM -- Processing refresh token request
iisexpress.exe Information: 0 : [Thinktecture.IdentityServer.Core.ResponseHandling.TokenResponseGenerator]: 2/22/2015 7:36:05 PM -- Processing refresh token request
iisexpress.exe Information: 0 : [Thinktecture.IdentityServer.Core.ResponseHandling.TokenResponseGenerator]: 2/22/2015 7:36:05 PM -- Processing refresh token request
Debug: [Thinktecture.IdentityServer.Core.Services.Default.DefaultTokenService]: 2/22/2015 7:36:05 PM -- Creating JWT access token
Debug: [Thinktecture.IdentityServer.Core.Services.Default.DefaultTokenService]: 2/22/2015 7:36:05 PM -- Creating JWT access token
Debug: [Thinktecture.IdentityServer.Core.Services.Default.DefaultTokenService]: 2/22/2015 7:36:05 PM -- Creating JWT access token
Debug: [Thinktecture.IdentityServer.Core.Services.Default.DefaultRefreshTokenService]: 2/22/2015 7:36:05 PM -- Updating refresh token
Debug: [Thinktecture.IdentityServer.Core.Services.Default.DefaultRefreshTokenService]: 2/22/2015 7:36:05 PM -- Token usage is one-time only. Generating new handle
Debug: [Thinktecture.IdentityServer.Core.Services.Default.DefaultRefreshTokenService]: 2/22/2015 7:36:05 PM -- Refresh token expiration is sliding - extending lifetime
Debug: [Thinktecture.IdentityServer.Core.Services.Default.DefaultRefreshTokenService]: 2/22/2015 7:36:05 PM -- Updating refresh token
Debug: [Thinktecture.IdentityServer.Core.Services.Default.DefaultRefreshTokenService]: 2/22/2015 7:36:05 PM -- Updating refresh token
Debug: [Thinktecture.IdentityServer.Core.Services.Default.DefaultRefreshTokenService]: 2/22/2015 7:36:05 PM -- Current lifetime: 111788
Debug: [Thinktecture.IdentityServer.Core.Services.Default.DefaultRefreshTokenService]: 2/22/2015 7:36:05 PM -- Token usage is one-time only. Generating new handle
Debug: [Thinktecture.IdentityServer.Core.Services.Default.DefaultRefreshTokenService]: 2/22/2015 7:36:05 PM -- Token usage is one-time only. Generating new handle
Debug: [Thinktecture.IdentityServer.Core.Services.Default.DefaultRefreshTokenService]: 2/22/2015 7:36:05 PM -- New lifetime: 1407788
Debug: [Thinktecture.IdentityServer.Core.Services.Default.DefaultRefreshTokenService]: 2/22/2015 7:36:05 PM -- Refresh token expiration is sliding - extending lifetime
Debug: [Thinktecture.IdentityServer.Core.Services.Default.DefaultRefreshTokenService]: 2/22/2015 7:36:05 PM -- Current lifetime: 111788
Debug: [Thinktecture.IdentityServer.Core.Services.Default.DefaultRefreshTokenService]: 2/22/2015 7:36:05 PM -- New lifetime: 1407788
Debug: [Thinktecture.IdentityServer.Core.Services.Default.DefaultRefreshTokenService]: 2/22/2015 7:36:05 PM -- Refresh token expiration is sliding - extending lifetime
Debug: [Thinktecture.IdentityServer.Core.Services.Default.DefaultRefreshTokenService]: 2/22/2015 7:36:05 PM -- Current lifetime: 111788
Debug: [Thinktecture.IdentityServer.Core.Services.Default.DefaultRefreshTokenService]: 2/22/2015 7:36:05 PM -- New lifetime: 1407788
A first chance exception of type 'System.Data.Entity.Core.OptimisticConcurrencyException' occurred in EntityFramework.dll
A first chance exception of type 'System.Data.Entity.Core.OptimisticConcurrencyException' occurred in EntityFramework.dll
A first chance exception of type 'System.Data.Entity.Core.OptimisticConcurrencyException' occurred in EntityFramework.dll
A first chance exception of type 'System.Data.Entity.Core.OptimisticConcurrencyException' occurred in EntityFramework.dll
A first chance exception of type 'System.Data.Entity.Core.OptimisticConcurrencyException' occurred in EntityFramework.dll
A first chance exception of type 'System.Data.Entity.Core.OptimisticConcurrencyException' occurred in EntityFramework.SqlServer.dll
A first chance exception of type 'System.Data.Entity.Core.OptimisticConcurrencyException' occurred in EntityFramework.dll
A first chance exception of type 'System.Data.Entity.Core.OptimisticConcurrencyException' occurred in EntityFramework.SqlServer.dll
A first chance exception of type 'System.Data.Entity.Infrastructure.DbUpdateConcurrencyException' occurred in EntityFramework.dll
A first chance exception of type 'System.Data.Entity.Infrastructure.DbUpdateConcurrencyException' occurred in EntityFramework.dll
A first chance exception of type 'System.Data.Entity.Infrastructure.DbUpdateConcurrencyException' occurred in mscorlib.dll
A first chance exception of type 'System.Data.Entity.Infrastructure.DbUpdateConcurrencyException' occurred in mscorlib.dll
A first chance exception of type 'System.Data.Entity.Infrastructure.DbUpdateConcurrencyException' occurred in mscorlib.dll
A first chance exception of type 'System.Data.Entity.Infrastructure.DbUpdateConcurrencyException' occurred in mscorlib.dll
A first chance exception of type 'System.Data.Entity.Infrastructure.DbUpdateConcurrencyException' occurred in mscorlib.dll
A first chance exception of type 'System.Data.Entity.Infrastructure.DbUpdateConcurrencyException' occurred in mscorlib.dll
A first chance exception of type 'System.Data.Entity.Infrastructure.DbUpdateConcurrencyException' occurred in mscorlib.dll
A first chance exception of type 'System.Data.Entity.Infrastructure.DbUpdateConcurrencyException' occurred in mscorlib.dll
A first chance exception of type 'System.Data.Entity.Infrastructure.DbUpdateConcurrencyException' occurred in mscorlib.dll
A first chance exception of type 'System.Data.Entity.Infrastructure.DbUpdateConcurrencyException' occurred in mscorlib.dll
A first chance exception of type 'System.Data.Entity.Infrastructure.DbUpdateConcurrencyException' occurred in mscorlib.dll
A first chance exception of type 'System.Data.Entity.Infrastructure.DbUpdateConcurrencyException' occurred in mscorlib.dll
A first chance exception of type 'System.Data.Entity.Infrastructure.DbUpdateConcurrencyException' occurred in mscorlib.dll
A first chance exception of type 'System.Data.Entity.Infrastructure.DbUpdateConcurrencyException' occurred in mscorlib.dll
A first chance exception of type 'System.Data.Entity.Infrastructure.DbUpdateConcurrencyException' occurred in mscorlib.dll
A first chance exception of type 'System.Data.Entity.Infrastructure.DbUpdateConcurrencyException' occurred in mscorlib.dll
A first chance exception of type 'System.Data.Entity.Infrastructure.DbUpdateConcurrencyException' occurred in mscorlib.dll
A first chance exception of type 'System.Data.Entity.Infrastructure.DbUpdateConcurrencyException' occurred in mscorlib.dll
A first chance exception of type 'System.Data.Entity.Infrastructure.DbUpdateConcurrencyException' occurred in mscorlib.dll
A first chance exception of type 'System.Data.Entity.Infrastructure.DbUpdateConcurrencyException' occurred in mscorlib.dll
A first chance exception of type 'System.Data.Entity.Infrastructure.DbUpdateConcurrencyException' occurred in mscorlib.dll
A first chance exception of type 'System.Data.Entity.Infrastructure.DbUpdateConcurrencyException' occurred in mscorlib.dll
A first chance exception of type 'System.Data.Entity.Infrastructure.DbUpdateConcurrencyException' occurred in mscorlib.dll
A first chance exception of type 'System.Data.Entity.Infrastructure.DbUpdateConcurrencyException' occurred in mscorlib.dll
iisexpress.exe Error: 0 : [Thinktecture.IdentityServer.Core.Configuration.Hosting.LogProviderExceptionLogger]: 2/22/2015 7:36:08 PM -- Unhandled exception
System.Data.Entity.Infrastructure.DbUpdateConcurrencyException: Store update, insert, or delete statement affected an unexpected number of rows (0). Entities may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=472540 for information on understanding and handling optimistic concurrency exceptions. ---> System.Data.Entity.Core.OptimisticConcurrencyException: Store update, insert, or delete statement affected an unexpected number of rows (0). Entities may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=472540 for information on understanding and handling optimistic concurrency exceptions.
   at System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.ValidateRowsAffected(Int64 rowsAffected, UpdateCommand source)
   at System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   at System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.<Update>b__2(UpdateTranslator ut)
   at System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update[T](T noChangesResult, Func`2 updateFunction)
   at System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update()
   at System.Data.Entity.Core.Objects.ObjectContext.<SaveChangesToStore>b__35()
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions options, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction)
   at System.Data.Entity.Core.Objects.ObjectContext.<>c__DisplayClass2a.<SaveChangesInternal>b__27()
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectContext.SaveChangesInternal(SaveOptions options, Boolean executeInExistingTransaction)
   at System.Data.Entity.Core.Objects.ObjectContext.SaveChanges(SaveOptions options)
   at System.Data.Entity.Internal.InternalContext.SaveChanges()
   --- End of inner exception stack trace ---
   at System.Data.Entity.Internal.InternalContext.SaveChanges()
   at System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   at System.Data.Entity.DbContext.SaveChanges()
   at Thinktecture.IdentityServer.Core.EntityFramework.BaseDbContext.SaveChanges() in d:\Dev\Thinktecture.IdentityServer.v3.EntityFramework\Source\Core.EntityFramework\DbContexts\BaseDbContext.cs:line 33
   at Thinktecture.IdentityServer.Core.EntityFramework.BaseTokenStore`1.RemoveAsync(String key) in d:\Dev\Thinktecture.IdentityServer.v3.EntityFramework\Source\Core.EntityFramework\Stores\BaseTokenStore.cs:line 89
   at Thinktecture.IdentityServer.Core.Services.Default.KeyHashingTransientDataRepository`1.RemoveAsync(String key) in c:\etc\Dropbox\thinktecture\IdentityServer.v3\Core\source\Core\Services\Default\KeyHashingTransientDataRepository.cs:line 90
   at Thinktecture.IdentityServer.Core.Services.Default.DefaultRefreshTokenService.<UpdateRefreshTokenAsync>d__7.MoveNext() in c:\etc\Dropbox\thinktecture\IdentityServer.v3\Core\source\Core\Services\Default\DefaultRefreshTokenService.cs:line 134
```

**Comment by brockallen** [comment]
Are you saying you have two different refresh token requests at the same time for the same refresh token?

**Comment by promontis** [comment]
Yeah, that's what I am saying. My app is making some concurrent requests (like 3), but since they all use the same access token, which is expired, the http handler handling those requests will try and refresh them using the refresh token. 

I could solve this within my app, but it seems to be the wrong place to fix this, or do you think otherwise? This would mean I would need to introduce some way of channeling the request so that I will not send concurrent requests (which would slow down my app).

I think IdSrv3 should gracefully handle concurrency issues like this. I've tested this and it works great, but I'm open for suggestions on different implementations.

**Comment by brockallen** [comment]
I don't know right now what the best approach will be... right now I'm just trying to understand what triggers it.

**Comment by leastprivilege** [comment]
This would mean I would need to introduce some way of channeling the request so that I will not send concurrent requests (which would slow down my app).

I think requests to the token service should be not concurrent. App requests are OK.

That said - we need to handle that more gracefully. But "one time only" semantics for refresh tokens means - well "one time only" ;)

**Comment by promontis** [comment]
> I think requests to the token service should be not concurrent. App requests are OK.

I agree, but the solution I've build is so elegant right now:
a custom AuthHttpHandler, which will add the auth header, make the api request and if it fails because of the token, it will try to refresh the token and then retry the api request.

**Comment by leastprivilege** [comment]
lol.

Maybe you should rather pro-actively cache the token and check the lifetime before using it.

**Comment by brockallen** [comment]
So what are we going to do with this issue?

**Comment by promontis** [comment]
I'm currently discussing this with Paul Betts. I'm using his awesome pipeline of prioritizing, throttling, redoing, etc http requests. Will probably just make one request for the refresh token. 

However, I still think you should handle concurrency issues more gracefully. But it's your call eventually.

**Comment by brockallen** [comment]
I'll close this now, as I don't foresee us making any changes in the core for this anytime soon. Sorry.
