### ISSUE TITLE
Error while configuring ScopeStore on IdentityServer3 (version 2.1)

### ISSUE THREAD

**Issue by amitpathak024** [IdentityServer/IdentityServer3.EntityFramework#79]
Hi,
I am new to IdentityServer3.I am getting the following error while configuring ScopeStore
{"Schema specified is not valid. Errors: \r\nThe relationship 'MaterdbModel.FK_dbo_ScopeClaims_dbo_Scopes_Scope_Id' 
was not loaded because the type 'MaterdbModel.ScopeClaim' is not available.\r\nThe following information may be useful in resolving the previous error:
\r\nThe required property 'Scope_Id' does not exist on the type 'IdentityServer3.EntityFramework.Entities.ScopeClaim'.\r\n\r\n"}.

Please have a look and update the codebase and nuget package asap.

Thanks,
Amit

**Comment by brockallen** [comment]
How did you create the DB? Did you use migrations?

https://identityserver.github.io/Documentation/docsv2/ef/migrations.html

**Comment by amitpathak024** [comment]
I created the DB using EntityFramework sample provided in Samples.

**Comment by brockallen** [comment]
Using migrations (the way our docs suggest)?

**Comment by amitpathak024** [comment]
Let me try it and let you know.I haven't used migrations.

**Comment by amitpathak024** [comment]
I am getting the following error : 
Checking if the context targets an existing database...
System.InvalidOperationException: Can not override the connection for this context with an EntityConnection because the original connection was a standard DbConnection.
   at System.Data.Entity.Internal.LazyInternalContext.OverrideConnection(IInternalConnection connection)
   at System.Data.Entity.Infrastructure.DbContextInfo.ConfigureContext(DbContext context)
   at System.Data.Entity.Internal.InternalContext.ApplyContextInfo(DbContextInfo info)
   at System.Data.Entity.Infrastructure.DbContextInfo.CreateInstance()
   at System.Data.Entity.Infrastructure.DbContextInfo..ctor(Type contextType, DbProviderInfo modelProviderInfo, AppConfig config, DbConnectionInfo connectionInfo, Func`1 resolver)
   at System.Data.Entity.Migrations.DbMigrator..ctor(DbMigrationsConfiguration configuration, DbContext usersContext, DatabaseExistenceState existenceState, Boolean calledByCreateDatabase)
   at System.Data.Entity.Migrations.DbMigrator..ctor(DbMigrationsConfiguration configuration)
   at System.Data.Entity.Migrations.Design.MigrationScaffolder..ctor(DbMigrationsConfiguration migrationsConfiguration)
   at System.Data.Entity.Migrations.Design.ToolingFacade.ScaffoldRunner.Run()
   at System.AppDomain.DoCallBack(CrossAppDomainDelegate callBackDelegate)
   at System.AppDomain.DoCallBack(CrossAppDomainDelegate callBackDelegate)
   at System.Data.Entity.Migrations.Design.ToolingFacade.Run(BaseRunner runner)
   at System.Data.Entity.Migrations.Design.ToolingFacade.ScaffoldInitialCreate(String language, String rootNamespace)
   at System.Data.Entity.Migrations.EnableMigrationsCommand.<>c__DisplayClass2.<.ctor>b__0()
   at System.Data.Entity.Migrations.MigrationsDomainCommand.Execute(Action command)
Can not override the connection for this context with an EntityConnection because the original connection was a standard DbConnection.

after running following command in PM console:

Enable-Migrations -MigrationsDirectory Migrations\OperationalConfiguration -ContextTypeName OperationalDbContext -ContextAssemblyName IdentityServer3.EntityFramework -ConnectionStringName materdbentities

**Comment by brockallen** [comment]
I'm not sure what that means. This sample has all the migrations up to our latest 2.2 release:

https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/EntityFramework

**Comment by amitpathak024** [comment]
I recreated the DB using EntityFramework sample (ver 2.2) and also updating the Identityserver3 Dll (ver 2.2) and still the same issue persists.Actually i am trying to create custom scopestore, the main page comes up but when i click on discovery document link on it, i get the following error : 
**Schema specified is not valid. Errors: 
The relationship 'TestingDBModel.FK_dbo_ScopeClaims_dbo_Scopes_Scope_Id' was not loaded because the type 'TestingDBModel.ScopeClaim' is not available.
The following information may be useful in resolving the previous error:
The required property 'Scope_Id' does not exist on the type 'IdentityServer3.EntityFramework.Entities.ScopeClaim'.
The relationship 'TestingDBModel.FK_dbo_ScopeSecrets_dbo_Scopes_Scope_Id' was not loaded because the type 'TestingDBModel.ScopeSecret' is not available.
The following information may be useful in resolving the previous error:
The required property 'Scope_Id' does not exist on the type 'IdentityServer3.EntityFramework.Entities.ScopeSecret'.**

**Comment by brockallen** [comment]
Sorry -- you're dealing with EF at this point. I don't have any suggestions to help.
